**PyTorch** идет предустановленным в Google Colab, просто импортируем

In [ ]:
import torch
import numpy as np

**Матричное умножение** - операция над матрицами, где результирующая матрица составлена скалярными произведениями строк и рядов

**Скалярное произведение** двух векторов - сумма произведений элементов в соответствующих позициях этих векторов

In [ ]:
v1 = np.array([1, 2])
v2 = np.array([3, 4])
np.dot(v1, v2)

11

In [ ]:
t1 = torch.Tensor([[1, 2], [3, 4]])
t2 = torch.ones(2, 2) * 2
print(t1)
print(t2)

tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 2.],
        [2., 2.]])


теперь умножим эти две матрицы операцией **@** (аналог - torch.**matmul**())

In [ ]:
t1 @ t2

tensor([[ 6.,  6.],
        [14., 14.]])

**Задание**: вычислить выражение

**Дано**: 2 матричных тензора **t1** и **t2**

In [ ]:
t1 = torch.stack([torch.Tensor([1, 1, 1, 1]) * n for n in range(1, 5)])
t2 = t1.transpose(-1, -2)
print(t1)
print(t2)

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.]])
tensor([[1., 2., 3., 4.],
        [1., 2., 3., 4.],
        [1., 2., 3., 4.],
        [1., 2., 3., 4.]])


**1**) Вычислить выражение **t3** = t1 ** 2 - t2 * 2 + t1 * 4

2) Сделать конкатенацию тензоров **t2** и **t3**, записать в тензор **t4** (должна получиться размерность 4 строки и 8 столбцов) 

Конкатенация - операция, в которой результирующая матрица составлена из рядов первой и второй матрицы, если конкатенация идет вдоль столбцов, или из столбцов первой и второй матрицы, если конкатенация идет вдоль строк. 

Делается оператором **torch.cat**(tensors, dim), где

**tensors** - список исходных тензоров

**dim** - измерение, вдоль которого делается конкатенация, 0 - вдоль столбцов, 1 - вдоль строк



3) Посчитать скалярное произведение **первой** и **последней** строки матрицы тензора **t4**